### ISSUE TITLE
src文件夹下的内容能否使用小写的文件夹

### ISSUE THREAD

**Issue by liudonghua123** [Tuisku-L/TaroDva.Demo#2]
之前写的很多东西，包括看其他人的代码等，一般都是用小写的文件夹，例如 components、models、utils、pages等，组件名一般首字母是大写的，我看这个 boilerplate 感觉总是有点别扭，不习惯。以下是其他一些 taro-dva 的项目结构。

![image](https://user-images.githubusercontent.com/2276718/59476590-0c051e00-8e84-11e9-88ac-ca5444743063.png)

![image](https://user-images.githubusercontent.com/2276718/59476611-2c34dd00-8e84-11e9-8ae1-b48afb4ca19f.png)

![image](https://user-images.githubusercontent.com/2276718/59476625-38209f00-8e84-11e9-9616-efe644465aa6.png)

**Comment by Woo0ood** [comment]
这个与 代码规范 和 个人习惯/喜好 相关的问题可以自行斟酌修改
因为我司的代码规范是这部分文件夹大写, 所以示例项目中就沿用了下来

如果个人需要修改, 自行修改 GenerateTemplate.js 中的文件模板和注意在 app.tsx 以及其他文件中的引用即可.
